# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe9cda4b8ec53abc8758a60dcf02976eb4dd43be278a302325e1b6b2955cc69037aa7e5bb56649581c6592a3165fe2a5178dfa3acdf90ee6329e1f11fea270da

test:
  secret_key_base: b0911e351cfcdf6fc064d2bd4f1e116ae4b3ff0b618590ec3d01caff7db22f67fe8e93edca5da6a3ee09d1214e5197dfe8fba3ffc458bfab09f7de882de89c36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
